Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
camry.predict(links)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[7], line 1[0m
[0;32m----> 1[0m [43mcamry[49m[38;5;241;43m.[39;49m[43mpredict[49m[43m([49m[43mlinks[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nrel/routee/powertrain/core/model.py:223[0m, in [0;36mModel.predict[0;34m(self, links_df, feature_columns, distance_column, apply_real_world_adjustment)[0m
[1;32m    221[0m     estimator [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mestimators[38;5;241m.[39mget(feature_set_id)
[1;32m    222[0m     [38;5;28;01mif[39;00m estimator [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 223[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    224[0m             [38;5;124m"[39m[38;5;124mThis model has multiple feature sets and no features were [39m[38;5;124m"[39m
[1;32m    225[0m             [38;5;124m"[39m[38;5;124mexplicitly provided. [39m[38;5;124m"[39m
[1;32m    226[0m             [38;5;124m"[39m[38;5;124mWe attempted to just use the columns in the incoming dataframe [39m[38;5;124m"[39m
[1;32m    227[0m             [38;5;124m"[39m[38;5;124mbut we couldn[39m[38;5;124m'[39m[38;5;124mt find an estiamtor that matches the features: [39m[38;5;124m"[39m
[1;32m    228[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mfeature_columns[38;5;132;01m}[39;00m[38;5;124m. [39m[38;5;124m"[39m
[1;32m    229[0m             [38;5;124m"[39m[38;5;124mPlease provide an explicit list of feature names to the features [39m[38;5;124m"[39m
[1;32m    230[0m             [38;5;124m"[39m[38;5;124mparamter of the predict method or provide a dataframe that only [39m[38;5;124m"[39m
[1;32m    231[0m             [38;5;124m"[39m[38;5;124mcontains the features you want to use. [39m[38;5;124m"[39m
[1;32m    232[0m             [38;5;124m"[39m[38;5;124mHere are the feature sets that can be used: [39m[38;5;124m"[39m
[1;32m    233[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00m[38;5;28mself[39m[38;5;241m.[39mfeature_set_lists[38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m    234[0m         )
[1;32m    235[0m [38;5;28;01melse[39;00m:
[1;32m    236[0m     feature_set_id [38;5;241m=[39m feature_names_to_id(feature_columns)

[0;31mValueError[0m: This model has multiple feature sets and no features were explicitly provided. We attempted to just use the columns in the incoming dataframe but we couldn't find an estiamtor that matches the features: ['speed_mph', 'previous_speed_mph', 'grade_dec', 'previous_grade_dec', 'entry_angle']. Please provide an explicit list of feature names to the features paramter of the predict method or provide a dataframe that only contains the features you want to use. Here are the feature sets that can be used: [['speed_mph'], ['grade_dec', 'speed_mph'], ['grade_dec', 'previous_grade_dec', 'previous_speed_mph', 'speed_mph'], ['entry_angle', 'exit_angle', 'grade_dec', 'previous_grade_dec', 'previous_speed_mph', 'speed_mph']]

